const DESIGN = {
  id: 1,
  name: "Personal Links",
  title: "losh_cherns",
  desc: "by Aleksey C",
  bio: "elite junior dev",
  imgURL: "https://bit.ly/dan-abramov",
  bgColor: "gray.800",
  font: "sans-serif",
  shape: "0px",
  variantColor: "",
  shadow: "",
  fontColor: "white",
  shadowColor: "black",
  public: true,
  buttonFontColor: "white",
  showLogo: true,
  links: [
    {
      id: 1,
      name: "YouTube",
      url: "https://www.youtube.com/",
      icon: "I_YT",
      active: true,
    },
    // {
    //   id: 2,
    //   name: "Facebook",
    //   url: "https://www.facebook.com/",
    //   icon: "I_FB",
    //   active: true,
    // },
    // {
    //   id: 3,
    //   name: "Twitter",
    //   url: "https://twitter.com/",
    //   icon: "I_TW",
    //   active: true,
    // },
    // {
    //   id: 4,
    //   name: "Instagram",
    //   url: "https://www.instagram.com/",
    //   icon: "I_IG",
    //   active: true,
    // },
    // {
    //   id: 5,
    //   name: "LinkedIn",
    //   url: "https://www.linkedin.com/",
    //   icon: "I_LI",
    //   active: true,
    // },
    // {
    //   id: 6,
    //   name: "Reddit",
    //   url: "https://www.reddit.com/",
    //   icon: "I_RD",
    //   active: true,
    // },
  ],
};

export default DESIGN;
